import json, os, re, math
from pathlib import Path

root = Path('/mnt/data/picklelevel_enrich/pickleball-site')

paddles = [
  {
    'brand':'JOOLA','model':'Ben Johns Perseus Pro IV','slug':'joola-ben-johns-perseus','style':'all-court','shape':'elongated','core':'Polymer honeycomb, 14/16mm options','face':'Carbon Friction Surface / TechFlex Power style platform','priceBand':'$$$','priceUsd':279.95,'priceSource':'Official brand MSRP / product page, verify before purchase','sourceName':'JOOLA product page','sourceUrl':'https://joola.com/products/joola-perseus-iv-16mm-pickleball-paddle-1','levels':['3.5','4.0','4.5','5.0'],'traits':['control','spin','reach','stability'],'usedBy':'Ben Johns signature line','reviewSignal':'Elite all-court reference paddle: reach, controlled power, and spin-friendly face for advanced players.','summary':'A premium elongated JOOLA signature paddle for players who can manage pace and want point-building control with finishing power.','ratings':{'power':8.5,'control':8.7,'spin':8.8,'forgiveness':8.1,'speed':7.6},
    'translations':{'ko':{'reviewSignal':'상급자용 올라운드 기준점에 가까운 패들입니다. 긴 리치, 컨트롤된 파워, 스핀 친화적인 표면을 원하는 플레이어에게 맞습니다.','summary':'속도를 다룰 수 있고 포인트 설계 능력을 키우려는 3.5 이상 플레이어에게 어울리는 프리미엄 엘롱게이티드 패들입니다.'}}
  },
  {'brand':'JOOLA','model':'Collin Johns Scorpeus Pro IV','slug':'joola-scorpeus','style':'hands','shape':'widebody','core':'Polymer honeycomb, 14/16mm options','face':'Carbon Friction Surface / TechFlex Power style platform','priceBand':'$$$','priceUsd':279.95,'priceSource':'Official brand MSRP / product line, verify before purchase','sourceName':'JOOLA Pro IV collection','sourceUrl':'https://joola.com/collections/pro-iv','levels':['3.0','3.5','4.0','4.5'],'traits':['forgiveness','hands','control','stability'],'usedBy':'Collin Johns signature line','reviewSignal':'Widebody profile for quick hands, blocks, resets, and kitchen exchanges.','summary':'A forgiving Scorpeus-style paddle for doubles players who value blocks, counters, and fast NVZ exchanges over maximum reach.','ratings':{'power':8.0,'control':8.8,'spin':8.5,'forgiveness':8.8,'speed':8.4},'translations':{'ko':{'reviewSignal':'와이드바디 형태라 빠른 손싸움, 블록, 리셋, 키친 교전에 강점이 있습니다.','summary':'최대 리치보다 관용성, 카운터, 빠른 NVZ 반응을 중시하는 더블스 플레이어에게 잘 맞습니다.'}}},
  {'brand':'Selkirk','model':'LUXX Control Air with InfiniGrit','slug':'selkirk-luxx-control-air','style':'control','shape':'elongated / invikta','core':'Thick control core','face':'InfiniGrit / carbon-fiberglass style face','priceBand':'$$$','priceUsd':280.00,'priceSource':'Selkirk collection listed price may include sale pricing; verify exact shape/color','sourceName':'Selkirk LUXX Control Air collection','sourceUrl':'https://www.selkirk.com/collections/luxx-control-air','levels':['3.0','3.5','4.0','4.5'],'traits':['control','forgiveness','touch','spin'],'usedBy':'Selkirk pro/control line','reviewSignal':'Premium control paddle built around touch, resets, drops, and finesse.','summary':'A soft-game paddle for players who want to keep balls low, place dinks, and reduce over-hitting without giving up premium construction.','ratings':{'power':7.1,'control':9.4,'spin':8.2,'forgiveness':8.8,'speed':7.4},'translations':{'ko':{'reviewSignal':'터치, 리셋, 드롭, 정교한 플레이를 중심으로 설계된 프리미엄 컨트롤 패들입니다.','summary':'공을 낮게 유지하고 딩크와 드롭의 안정성을 높이고 싶은 플레이어에게 적합합니다.'}}},
  {'brand':'Selkirk','model':'VANGUARD Power Air Invikta','slug':'selkirk-power-air','style':'power','shape':'elongated / invikta','core':'Performance polymer','face':'Hybrid performance face','priceBand':'$$$','priceUsd':250.00,'priceSource':'Typical Selkirk premium-line MSRP / collection pricing, verify current sale','sourceName':'Selkirk Invikta collection','sourceUrl':'https://www.selkirk.com/collections/invikta-paddles','levels':['3.5','4.0','4.5','5.0'],'traits':['power','spin','maneuverability'],'usedBy':'Selkirk power line','reviewSignal':'Power-forward paddle for players who already control pop and want aggressive finishing.','summary':'Best treated as an attacking paddle: helpful for drives and speed-ups, less forgiving for players who still float resets.','ratings':{'power':9.2,'control':7.1,'spin':8.7,'forgiveness':7.2,'speed':8.2},'translations':{'ko':{'reviewSignal':'반발력을 다룰 수 있는 플레이어가 공격성과 결정력을 높일 때 좋은 파워형 패들입니다.','summary':'드라이브와 스피드업에는 유리하지만 리셋이 뜨는 플레이어라면 적응 시간이 필요합니다.'}}},
  {'brand':'CRBN','model':'1X Power Series','slug':'crbn-1x-power-series','style':'power','shape':'elongated','core':'Polypropylene honeycomb','face':'Raw carbon fiber with power layer','priceBand':'$$$','priceUsd':229.99,'priceSource':'Official CRBN X Series pricing / verify variant','sourceName':'CRBN 1X Power Series','sourceUrl':'https://crbnpickleball.com/products/crbn-1x-power-series-pickleball-paddle','levels':['3.5','4.0','4.5','5.0'],'traits':['power','spin','reach'],'usedBy':'CRBN pro/team users vary by season','reviewSignal':'Raw-carbon elongated power paddle for aggressive drives and added reach.','summary':'A strong option when you want power and spin from an elongated shape, but it rewards clean contact and confident swing mechanics.','ratings':{'power':9.1,'control':7.6,'spin':8.9,'forgiveness':7.7,'speed':7.5},'translations':{'ko':{'reviewSignal':'공격적인 드라이브와 리치를 원하는 플레이어를 위한 로우 카본 엘롱게이티드 파워 패들입니다.','summary':'파워와 스핀을 동시에 원할 때 좋지만, 깨끗한 임팩트와 안정된 스윙이 필요합니다.'}}},
  {'brand':'CRBN','model':'2X Power Series','slug':'crbn-2x-power-series','style':'all-court','shape':'widebody','core':'Polypropylene honeycomb','face':'Raw carbon fiber with power layer','priceBand':'$$$','priceUsd':229.99,'priceSource':'Official CRBN X Series pricing / verify variant','sourceName':'CRBN X Series collection','sourceUrl':'https://crbnpickleball.com/collections/crbn-power-series-pickleball-paddles','levels':['3.0','3.5','4.0','4.5'],'traits':['forgiveness','spin','hands','power'],'usedBy':'CRBN pro/team users vary by season','reviewSignal':'Wider X Series alternative for players who want power, spin, and a bigger sweet spot.','summary':'A more forgiving power-series shape than a blade; useful for doubles players who need quick blocks and stable counters.','ratings':{'power':8.6,'control':8.0,'spin':8.8,'forgiveness':8.6,'speed':8.2},'translations':{'ko':{'reviewSignal':'파워와 스핀을 유지하면서 더 넓은 스윗스팟을 원하는 플레이어에게 맞는 X 시리즈 대안입니다.','summary':'블레이드형보다 관용성이 높아 더블스의 블록과 안정적인 카운터에 유리합니다.'}}},
  {'brand':'Six Zero','model':'Double Black Diamond Control','slug':'six-zero-double-black-diamond-control','style':'all-court','shape':'hybrid','core':'Polymer 16mm','face':'Raw carbon fiber','priceBand':'$$','priceUsd':180.00,'priceSource':'Official Six Zero product price may vary by region/promotions','sourceName':'Six Zero DBD Control','sourceUrl':'https://www.sixzeropickleball.com/products/double-black-diamond','levels':['3.0','3.5','4.0','4.5'],'traits':['control','spin','balance','value'],'usedBy':'Six Zero team / community favorite','reviewSignal':'Value-friendly all-court benchmark with a balanced control, spin, and power profile.','summary':'A popular step-up paddle for improving players who want modern raw-carbon feel without jumping to the most expensive tier.','ratings':{'power':8.1,'control':8.8,'spin':8.8,'forgiveness':8.2,'speed':8.1},'translations':{'ko':{'reviewSignal':'컨트롤, 스핀, 파워 밸런스가 좋아 가성비 높은 올라운드 기준점으로 자주 언급됩니다.','summary':'최고가 라인까지 가지 않고 현대적인 로우 카본 감각을 경험하고 싶은 성장형 플레이어에게 좋습니다.'}}},
  {'brand':'Six Zero','model':'Ruby','slug':'six-zero-ruby','style':'spin','shape':'hybrid','core':'Polymer 16mm','face':'Aramid / composite weave','priceBand':'$$$','priceUsd':200.00,'priceSource':'Official Six Zero product price may vary by availability','sourceName':'Six Zero Ruby','sourceUrl':'https://www.sixzeropickleball.com/products/ruby','levels':['3.5','4.0','4.5','5.0'],'traits':['spin','control','stability'],'usedBy':'Six Zero team / advanced users','reviewSignal':'Distinct aramid-face paddle often discussed for spin, feel, and stability.','summary':'For players who want a different face feel from standard carbon and prioritize controlled spin plus a connected touch response.','ratings':{'power':8.0,'control':8.9,'spin':9.2,'forgiveness':8.0,'speed':7.9},'translations':{'ko':{'reviewSignal':'아라미드 계열 표면으로 스핀, 타구감, 안정성 면에서 차별화된 패들로 언급됩니다.','summary':'일반 카본과 다른 감각, 컨트롤된 스핀, 손에 붙는 터치를 원하는 플레이어에게 적합합니다.'}}},
  {'brand':'Paddletek','model':'Bantam TKO-C','slug':'paddletek-bantam-tko-c','style':'power','shape':'elongated','core':'Bantam polymer core','face':'PT-700 unidirectional raw carbon fiber','priceBand':'$$$','priceUsd':199.99,'priceSource':'Official product page sale price, verify current price','sourceName':'Paddletek Bantam TKO-C','sourceUrl':'https://www.paddletek.com/products/bantam-tko-c','levels':['3.5','4.0','4.5','5.0'],'traits':['power','reach','stability','spin'],'usedBy':'Designed with Christian Alshon','reviewSignal':'Power-and-reach paddle designed with Christian Alshon; built for serious pace creation.','summary':'A tournament-style power paddle for confident attackers who want elongated reach and a raw-carbon striking surface.','ratings':{'power':9.0,'control':7.6,'spin':8.8,'forgiveness':7.7,'speed':7.7},'translations':{'ko':{'reviewSignal':'Christian Alshon과 함께 설계된 파워·리치 중심 패들로 강한 페이스를 만들고 싶은 플레이어에게 맞습니다.','summary':'긴 리치와 로우 카본 타구면을 활용해 공격적인 경기를 운영하는 상급자에게 적합합니다.'}}},
  {'brand':'Paddletek','model':'Tempest Wave Pro v3','slug':'paddletek-tempest-wave-pro','style':'control','shape':'traditional','core':'Polymer honeycomb','face':'Textured graphite','priceBand':'$$','priceUsd':179.99,'priceSource':'Typical Paddletek Tempest premium control price, verify current retailer/brand listing','sourceName':'Paddletek Tempest collection','sourceUrl':'https://www.paddletek.com/collections/tempest-series','levels':['2.5','3.0','3.5','4.0'],'traits':['control','touch','forgiveness'],'usedBy':'Paddletek control line','reviewSignal':'Long-running control paddle for touch, resets, and developing all-court consistency.','summary':'A familiar control option for players who prefer a classic shape and predictable response over maximum power.','ratings':{'power':6.9,'control':9.0,'spin':7.2,'forgiveness':8.4,'speed':8.0},'translations':{'ko':{'reviewSignal':'터치, 리셋, 안정적인 올라운드 플레이를 익히는 데 적합한 장수 컨트롤 패들입니다.','summary':'최대 파워보다 예측 가능한 반응과 클래식한 형태를 선호하는 플레이어에게 어울립니다.'}}},
  {'brand':'Engage','model':'Pursuit Pro1 Power Series','slug':'engage-pursuit-pro1','style':'all-court','shape':'elongated / hybrid / widebody options','core':'SpinCore / polymer control platform','face':'Raw carbon composite','priceBand':'$$$','priceUsd':259.99,'priceSource':'Official collection shows MSRP/sale variations by shape and thickness','sourceName':'Engage Pursuit Pro1 Power Series','sourceUrl':'https://engagepickleball.com/collections/pursuit-pro1-power-series-line-of-paddles','levels':['3.0','3.5','4.0','4.5'],'traits':['control','spin','stability','power'],'usedBy':'Engage pro/team users vary by season','reviewSignal':'Shape-flexible Pro1 line built for power, spin, and stable acceleration.','summary':'Useful as a comparison family: choose shape and thickness around how much reach, pop, and control you want.','ratings':{'power':8.8,'control':8.1,'spin':8.8,'forgiveness':8.0,'speed':7.9},'translations':{'ko':{'reviewSignal':'형태와 두께 선택지가 넓고 파워, 스핀, 안정적인 가속을 목표로 한 Pro1 라인입니다.','summary':'리치, 반발력, 컨트롤 중 무엇을 우선할지에 따라 형태와 두께를 선택하는 비교형 패들입니다.'}}},
  {'brand':'Gearbox','model':'Pro Ultimate Elongated','slug':'gearbox-pro-power-elongated','style':'power','shape':'elongated','core':'SSTCore / solid-style construction','face':'Carbon composite with TXR-style grip technology','priceBand':'$$$','priceUsd':274.99,'priceSource':'Official product page listed price','sourceName':'Gearbox Pro Ultimate Elongated','sourceUrl':'https://gearboxsports.com/products/pro-ultimate-elongated','levels':['4.0','4.5','5.0'],'traits':['power','reach','stability'],'usedBy':'Gearbox pro-grade line','reviewSignal':'High-performance elongated paddle with distinctive Gearbox construction and strong power/control mix.','summary':'Demo first if possible: the construction feel is different from conventional honeycomb paddles and rewards advanced touch calibration.','ratings':{'power':9.1,'control':8.2,'spin':8.4,'forgiveness':8.0,'speed':7.4},'translations':{'ko':{'reviewSignal':'Gearbox 특유의 구조와 강한 파워·컨트롤 조합을 가진 고성능 엘롱게이티드 패들입니다.','summary':'일반 허니컴 패들과 감각이 달라 가능하면 시타 후 선택하는 것이 좋습니다.'}}},
  {'brand':'Gearbox','model':'CX14','slug':'gearbox-cx14','style':'control','shape':'elongated / quad','core':'SSTCore solid-span control construction','face':'Carbon fiber','priceBand':'$$$','priceUsd':199.99,'priceSource':'Typical Gearbox CX line pricing varies by retailer and closeout status','sourceName':'Gearbox pickleball collection','sourceUrl':'https://gearboxsports.com/pages/pickleball','levels':['3.0','3.5','4.0'],'traits':['control','touch','durability'],'usedBy':'Gearbox control users','reviewSignal':'Distinctive durable control feel, often chosen by players who like Gearbox construction.','summary':'A control-oriented Gearbox option for players who value durability and feedback more than trampoline-like pop.','ratings':{'power':7.2,'control':8.9,'spin':7.6,'forgiveness':7.8,'speed':8.1},'translations':{'ko':{'reviewSignal':'Gearbox 특유의 내구성과 컨트롤 감각을 선호하는 플레이어가 선택하는 라인입니다.','summary':'강한 반발력보다 내구성, 피드백, 안정적인 컨트롤을 중시하는 플레이어에게 맞습니다.'}}},
  {'brand':'Diadem','model':'Edge 18K','slug':'diadem-edge-18k','style':'spin','shape':'hybrid','core':'Polymer honeycomb 16mm','face':'3D 18K carbon fiber weave','priceBand':'$$$','priceUsd':229.95,'priceSource':'Official product/collection price may vary by Edge 18K variant','sourceName':'Diadem Edge 18K','sourceUrl':'https://diademsports.com/products/diadem-edge-18k','levels':['3.0','3.5','4.0','4.5'],'traits':['spin','control','forgiveness'],'usedBy':'Diadem team / spin-control users','reviewSignal':'3D 18K woven face paddle focused on spin, control, and a premium feel.','summary':'A spin-forward hybrid for players who want a recognizable face texture and a controlled 16mm response.','ratings':{'power':7.8,'control':8.8,'spin':9.1,'forgiveness':8.2,'speed':7.8},'translations':{'ko':{'reviewSignal':'3D 18K 우븐 표면을 활용해 스핀, 컨트롤, 프리미엄 타구감을 강조한 패들입니다.','summary':'확실한 표면감과 16mm 컨트롤 반응을 원하는 스핀 중심 플레이어에게 좋습니다.'}}},
  {'brand':'Diadem','model':'Warrior Edge','slug':'diadem-warrior-edge','style':'all-court','shape':'traditional / hybrid','core':'Polymer honeycomb','face':'Carbon fiber','priceBand':'$$','priceUsd':199.95,'priceSource':'Typical Diadem Warrior/Edge line pricing; verify exact model availability','sourceName':'Diadem paddle collection','sourceUrl':'https://diademsports.com/collections/edge-paddles','levels':['2.5','3.0','3.5','4.0'],'traits':['balance','control','forgiveness'],'usedBy':'Diadem team / all-court users','reviewSignal':'Balanced all-court model for players who want control without a very muted feel.','summary':'A practical middle ground for players moving from starter paddles to a more serious all-court setup.','ratings':{'power':7.7,'control':8.3,'spin':8.0,'forgiveness':8.1,'speed':7.9},'translations':{'ko':{'reviewSignal':'지나치게 먹먹하지 않은 컨트롤과 밸런스를 원하는 플레이어에게 맞는 올라운드형 모델입니다.','summary':'입문용에서 벗어나 본격적인 올라운드 세팅으로 넘어갈 때 비교하기 좋은 선택지입니다.'}}},
  {'brand':'Vatic Pro','model':'Prism Flash','slug':'vatic-pro-prism-flash','style':'control','shape':'hybrid','core':'Optimized C7 polymer honeycomb 16mm','face':'TORAY T700 raw carbon fiber','priceBand':'$$','priceUsd':99.99,'priceSource':'Official Vatic Pro PRISM collection price','sourceName':'Vatic Pro PRISM collection','sourceUrl':'https://vaticpro.com/collections/prism','levels':['2.5','3.0','3.5','4.0'],'traits':['value','control','spin'],'usedBy':'Community value favorite','reviewSignal':'Affordable raw-carbon control paddle with strong value and a forgiving hybrid shape.','summary':'One of the easiest recommendations for players who want genuine control/spin performance without a premium price tag.','ratings':{'power':7.0,'control':9.0,'spin':8.7,'forgiveness':8.4,'speed':8.2},'translations':{'ko':{'reviewSignal':'가격 대비 로우 카본 컨트롤 성능과 하이브리드 형태의 관용성이 좋은 가성비 패들입니다.','summary':'프리미엄 가격 없이 컨트롤과 스핀 성능을 체감하고 싶은 플레이어에게 추천하기 쉽습니다.'}}},
  {'brand':'Vatic Pro','model':'Saga','slug':'vatic-pro-saga','style':'all-court','shape':'hybrid','core':'10mm celled polypropylene honeycomb','face':'Composite carbon surface','priceBand':'$$','priceUsd':99.99,'priceSource':'Official Vatic Pro all-paddles listing','sourceName':'Vatic Pro paddles','sourceUrl':'https://vaticpro.com/collections/paddles','levels':['3.0','3.5','4.0','4.5'],'traits':['balance','spin','stability','value'],'usedBy':'Vatic Pro users / value hunters','reviewSignal':'Modern all-court option with low entry price and broad level fit.','summary':'A budget-conscious all-court comparison paddle for players who want balance rather than a pure control or pure power build.','ratings':{'power':7.7,'control':8.3,'spin':8.3,'forgiveness':8.0,'speed':8.1},'translations':{'ko':{'reviewSignal':'낮은 가격대와 넓은 레벨 적합성을 가진 현대적인 올라운드 선택지입니다.','summary':'순수 컨트롤이나 순수 파워보다 밸런스를 원하는 가성비 플레이어에게 비교 가치가 있습니다.'}}},
  {'brand':'ProKennex','model':'Black Ace Pro','slug':'prokennex-black-ace-pro','style':'power','shape':'traditional','core':'Polymer / kinetic system','face':'Toray carbon fiber style face','priceBand':'$$$','priceUsd':250.00,'priceSource':'Typical brand MSRP/retailer price; verify current availability','sourceName':'ProKennex Pickleball','sourceUrl':'https://prokennex-pickleball.com/','levels':['3.5','4.0','4.5','5.0'],'traits':['power','maneuverability','arm-comfort','pop'],'usedBy':'ProKennex power/comfort users','reviewSignal':'Powerful, quick-hand paddle often discussed for pop and arm-comfort technology.','summary':'A distinctive pick for players seeking fast response and ProKennex vibration-management ideas in a compact power package.','ratings':{'power':9.0,'control':7.3,'spin':7.7,'forgiveness':7.4,'speed':8.7},'translations':{'ko':{'reviewSignal':'반발력과 빠른 손, 팔 부담 완화 기술로 자주 언급되는 파워형 패들입니다.','summary':'빠른 반응과 ProKennex 특유의 진동 관리 기술을 원하는 플레이어에게 맞습니다.'}}},
  {'brand':'Franklin','model':'C45 Carbon Fiber Series','slug':'franklin-c45','style':'all-court','shape':'hybrid / elongated options','core':'PowerFlex polymer, 12.7/14/16mm variants','face':'Carbon fiber / thermoformed unibody series','priceBand':'$$','priceUsd':179.99,'priceSource':'Official Franklin C45 series price varies by model/variant','sourceName':'Franklin C45 Carbon Fiber Series','sourceUrl':'https://franklinsports.com/c45-carbon','levels':['3.0','3.5','4.0','4.5'],'traits':['balance','spin','value'],'usedBy':'Franklin pro line / Anna Leigh Waters signature variants','reviewSignal':'Mainstream carbon series with multiple variants and broad availability.','summary':'Good for comparing thickness and shape options from a large sporting-goods brand; check exact variant before buying.','ratings':{'power':8.0,'control':8.1,'spin':8.3,'forgiveness':8.0,'speed':8.0},'translations':{'ko':{'reviewSignal':'여러 변형 모델과 높은 접근성을 가진 대형 스포츠 브랜드의 카본 시리즈입니다.','summary':'두께와 형태 선택지를 비교하기 좋으며, 구매 전 정확한 모델명을 확인하는 것이 중요합니다.'}}},
  {'brand':'HEAD','model':'Radical TOUR15 / TOUR EX15','slug':'head-radical-tour','style':'all-court','shape':'traditional / elongated EX','core':'Thermoformed 15mm platform','face':'Micro-forged raw carbon face','priceBand':'$$','priceUsd':169.95,'priceSource':'Official HEAD Radical collection listing','sourceName':'HEAD Radical pickleball paddles','sourceUrl':'https://www.head.com/en_US/shop-pickleball/paddle/radical','levels':['2.5','3.0','3.5','4.0'],'traits':['forgiveness','control','stability'],'usedBy':'HEAD team / racquet-sports crossover players','reviewSignal':'Accessible all-court radical line from a major racquet-sports brand.','summary':'Useful for players coming from tennis who want a familiar brand, solid construction, and a less extreme price point.','ratings':{'power':7.7,'control':8.2,'spin':8.1,'forgiveness':8.2,'speed':8.0},'translations':{'ko':{'reviewSignal':'라켓 스포츠 대형 브랜드 HEAD의 접근성 좋은 올라운드 라인입니다.','summary':'테니스 경험자가 익숙한 브랜드와 안정적인 구조, 비교적 합리적인 가격대를 원할 때 보기 좋습니다.'}}},
  {'brand':'Volair','model':'Mach 2 Forza','slug':'volair-mach-2-forza','style':'control','shape':'widebody','core':'Polypropylene 14/16mm options','face':'Raw carbon fiber','priceBand':'$$','priceUsd':119.99,'priceSource':'Official product page listed regular price','sourceName':'Volair Mach 2 Forza','sourceUrl':'https://volair.com/products/mach-2-forza-pickleball-paddle','levels':['3.0','3.5','4.0','4.5'],'traits':['hands','forgiveness','spin','value'],'usedBy':'Volair team / widebody control users','reviewSignal':'Widebody control paddle with strong spin, forgiveness, and a budget-friendly price.','summary':'A compelling doubles paddle for players who miss the sweet spot less often with a wider face and like a controlled 16mm feel.','ratings':{'power':7.4,'control':8.9,'spin':8.8,'forgiveness':9.0,'speed':8.5},'translations':{'ko':{'reviewSignal':'스핀, 관용성, 합리적인 가격을 갖춘 와이드바디 컨트롤 패들입니다.','summary':'넓은 페이스로 미스히트를 줄이고 16mm 컨트롤 감각을 원하는 더블스 플레이어에게 매력적입니다.'}}},
  {'brand':'Bread & Butter','model':'The Filth 16mm','slug':'bread-and-butter-filth','style':'power','shape':'elongated','core':'Polymer 16mm thermoformed','face':'Raw T-700 carbon fiber','priceBand':'$$','priceUsd':165.00,'priceSource':'Official Bread & Butter product pricing may vary with bundles/promos','sourceName':'Bread & Butter The Filth','sourceUrl':'https://www.bnbpickleball.com/products/the-filth','levels':['3.0','3.5','4.0','4.5'],'traits':['power','spin','reach','value'],'usedBy':'Bread & Butter community / direct-to-consumer users','reviewSignal':'Popular direct-to-consumer power/spin paddle with a distinctive brand personality.','summary':'A fun, aggressive option for players who want elongated reach and thermoformed power without luxury-tier pricing.','ratings':{'power':8.7,'control':7.8,'spin':8.6,'forgiveness':7.7,'speed':7.7},'translations':{'ko':{'reviewSignal':'독특한 브랜드 감성과 파워·스핀 성향으로 인기가 있는 DTC 패들입니다.','summary':'고가 프리미엄 라인까지 가지 않고 엘롱게이티드 리치와 써모폼 파워를 원하는 플레이어에게 좋습니다.'}}},
  {'brand':'Friday','model':'Original Paddle','slug':'friday-original','style':'value','shape':'hybrid','core':'Polymer thermoformed starter platform','face':'Carbon fiber style surface','priceBand':'$','priceUsd':69.00,'priceSource':'Official Friday pricing/bundle offers vary; verify current checkout price','sourceName':'Friday Pickleball Paddle','sourceUrl':'https://fridaypickle.com/products/friday-paddle','levels':['2.0','2.5','3.0','3.5'],'traits':['value','forgiveness','control'],'usedBy':'Recreational and improving players','reviewSignal':'Budget-friendly, forgiving starter paddle designed to make upgrading less expensive.','summary':'Best for new players who need a forgiving carbon-style paddle and would rather invest savings into lessons or court time.','ratings':{'power':7.0,'control':8.0,'spin':7.8,'forgiveness':8.7,'speed':8.1},'translations':{'ko':{'reviewSignal':'입문자가 부담 없이 업그레이드하기 좋은 관용성 높은 가성비 스타터 패들입니다.','summary':'새 플레이어가 레슨이나 코트 시간에 더 투자하면서도 괜찮은 카본 스타일 패들을 쓰고 싶을 때 좋습니다.'}}},
  {'brand':'ONIX','model':'Evoke Premier','slug':'onix-evoke-premier','style':'power','shape':'elongated / impact shape','core':'Polypropylene honeycomb','face':'Composite / DF composite face','priceBand':'$$','priceUsd':149.99,'priceSource':'Official ONIX pricing varies by color/version; verify current product page','sourceName':'ONIX Evoke Premier','sourceUrl':'https://www.onixpickleball.com/products/evoke-premier-pickleball-paddle','levels':['3.0','3.5','4.0'],'traits':['power','reach','pop'],'usedBy':'Co-developed with Matt Wright and Lucy Kovalova line','reviewSignal':'Long-running power paddle with reach-oriented shape and tournament approval positioning.','summary':'A known power-oriented model to compare against newer raw-carbon paddles, especially for players who like a composite pop feel.','ratings':{'power':8.5,'control':7.2,'spin':7.5,'forgiveness':7.8,'speed':7.8},'translations':{'ko':{'reviewSignal':'리치 중심 형태와 토너먼트 승인 포지셔닝을 갖춘 장수 파워 패들입니다.','summary':'최신 로우 카본 패들과 비교해 볼 만한 파워형 모델로, 컴포지트 반발감을 좋아하는 플레이어에게 맞습니다.'}}},
]

players = [
  {'name':'Ben Johns','slug':'ben-johns','country':'United States','countryCode':'USA','style':'All-court control with elite point construction','skills':['Third-shot variety','Dink patience','Counter timing','Pattern play','Two-handed backhand'],'achievements':['PPA profile describes him as one of the most dominant players in professional pickleball history.','Known for titles across singles, men’s doubles, and mixed doubles.','Signature JOOLA athlete and instruction/content entrepreneur.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'JOOLA Ben Johns signature line','watch':'Study how he changes pace without giving opponents attackable height.','bio':'Ben Johns grew up in Maryland, played multiple racquet sports, and developed into the benchmark modern male pickleball player. His game is built on patient point construction, calm hands at the kitchen, precise pattern selection, and the ability to shift from soft pressure to sudden offense. Off court, he has also built instructional and pickleball-related businesses, which makes his profile useful for both player analysis and sport-business content.','hometown':'Laytonsville, Maryland / Boca Raton, Florida listed on tour profiles','age':'27','height':'6 ft 1 in / 185 cm','turnedPro':'2016','plays':'Right-handed','resides':'Boca Raton, Florida','officialProfile':'https://ppatour.com/athlete/ben-johns/','secondaryProfile':'https://www.pickleball.com/players/ben-johns','translations':{'ko':{'style':'엘리트 포인트 설계 능력을 가진 올라운드 컨트롤형 선수','bio':'Ben Johns는 메릴랜드에서 성장했고 여러 라켓 스포츠 경험을 바탕으로 현대 남자 피클볼의 기준점 같은 선수로 평가받습니다. 인내심 있는 포인트 구성, 키친에서의 침착한 손싸움, 정교한 패턴 선택, 소프트 게임에서 갑작스러운 공격 전환이 핵심입니다. 코트 밖에서는 교육 콘텐츠와 피클볼 관련 사업도 운영해 선수 분석뿐 아니라 스포츠 비즈니스 콘텐츠로도 확장성이 큽니다.','watch':'공격 가능한 높이를 주지 않으면서 템포를 바꾸는 방식을 관찰하세요.'}}},
  {'name':'Anna Leigh Waters','slug':'anna-leigh-waters','country':'United States','countryCode':'USA','style':'Explosive pressure and fast kitchen attacks','skills':['Fast hands','Speed-ups','Court coverage','Mixed doubles pressure','Attack disguise'],'achievements':['PPA profile identifies her as a world No. 1 level player across women’s singles, doubles, and mixed doubles.','Youngest-generation star who helped define a faster attacking style.','Known for triple-crown dominance and a highly visible professional brand.'],'events':['Singles','Women’s doubles','Mixed doubles'],'paddle':'Franklin / signature or sponsored line varies by season','watch':'Watch how quickly neutral balls become attacks.','bio':'Anna Leigh Waters discovered pickleball as a child and rose unusually quickly, turning a compact, aggressive style into one of the sport’s most copied patterns. Her mother Leigh Waters has been central to her development and coaching. Her match clips are excellent study material for first-strike pressure, fast counters, and how to control the middle in mixed doubles.','hometown':'Boynton Beach, Florida / Florida tour profile','age':'19','height':'5 ft / 152 cm listed in public profiles','turnedPro':'2019','plays':'Right-handed','resides':'Florida','officialProfile':'https://ppatour.com/athlete/anna-leigh-waters/','secondaryProfile':'https://www.pickleball.com/players/anna-leigh-waters','translations':{'ko':{'style':'폭발적인 압박과 빠른 키친 공격을 앞세운 선수','bio':'Anna Leigh Waters는 어린 나이에 피클볼을 시작해 매우 빠르게 정상권에 올랐고, 작고 빠른 스윙과 공격적인 전개로 많은 플레이어가 참고하는 스타일을 만들었습니다. 어머니 Leigh Waters가 코칭과 성장 과정에서 큰 역할을 했습니다. 중립구를 즉시 공격으로 바꾸는 능력, 빠른 카운터, 혼합복식에서 중앙을 장악하는 방식을 공부하기 좋습니다.','watch':'중립적인 공이 얼마나 빨리 공격 기회로 바뀌는지 보세요.'}}},
  {'name':'Federico Staksrud','slug':'federico-staksrud','country':'Argentina / United States scene','countryCode':'ARG','style':'Aggressive singles pressure and disciplined baseline patterns','skills':['Singles movement','Drive patterns','Serve pressure','Transition attacks','Forehand control'],'achievements':['PPA profile lists him as a top men’s singles contender and active doubles/mixed competitor.','Buenos Aires tennis background before switching into professional pickleball.','Known for persistent singles pressure and disciplined pattern play.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'Sponsored equipment varies by season','watch':'Track how he builds singles points before finishing.','bio':'Federico Staksrud grew up in Buenos Aires and came from a competitive tennis background before moving through U.S. college tennis and coaching into pickleball. His game is especially useful for studying singles: serve pressure, repeatable baseline patterns, and how to turn a neutral drive into a transition attack.','hometown':'Buenos Aires, Argentina','age':'—','height':'—','turnedPro':'2021/2022 era','plays':'Right-handed','resides':'United States tour scene','officialProfile':'https://ppatour.com/athlete/federico-staksrud/','secondaryProfile':'https://pickleball.com/players/federico-staksrud','translations':{'ko':{'style':'강한 싱글 압박과 규율 있는 베이스라인 패턴을 가진 선수','bio':'Federico Staksrud는 부에노스아이레스에서 성장했고 테니스 배경을 바탕으로 미국 대학 테니스와 코칭을 거쳐 피클볼로 전향했습니다. 서브 압박, 반복 가능한 베이스라인 패턴, 중립 드라이브를 전환 공격으로 연결하는 방식이 특히 싱글스 학습에 좋습니다.','watch':'싱글 포인트를 마무리하기 전 어떤 방식으로 우위를 쌓는지 추적하세요.'}}},
  {'name':'JW Johnson','slug':'jw-johnson','country':'United States','countryCode':'USA','style':'Calm counters, compact hands, and precise all-court play','skills':['Counter blocks','Soft resets','Two-handed backhand','Doubles spacing','Tempo control'],'achievements':['PPA/Pickleball.com profiles highlight his early elite success and all-discipline relevance.','Known for a calm court presence and compact counter mechanics.','Part of a high-level pickleball family with Jorja Johnson.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'Franklin / sponsored line varies by season','watch':'Watch the short swing on counters and resets.','bio':'JW Johnson grew up in Kansas and moved with his family to Naples, Florida, where tennis and community play helped lead him into pickleball. His playing style is a model for compact efficiency: minimal extra motion, excellent resets, and counters that look calm even under speed.','hometown':'Pittsburg, Kansas / Naples, Florida','age':'—','height':'—','turnedPro':'Teen elite era','plays':'Right-handed','resides':'Florida','officialProfile':'https://ppatour.com/athlete/jw-johnson/','secondaryProfile':'https://pickleball.com/players/jw-johnson','translations':{'ko':{'style':'침착한 카운터, 짧은 스윙, 정교한 올라운드 플레이가 특징인 선수','bio':'JW Johnson은 캔자스에서 성장한 뒤 가족과 함께 플로리다 네이플스로 이동했고, 테니스와 지역 커뮤니티 플레이를 통해 피클볼에 깊이 들어왔습니다. 불필요한 동작이 적고 리셋과 카운터가 매우 간결해 속도전 상황에서도 안정적인 모델로 참고하기 좋습니다.','watch':'카운터와 리셋에서 스윙이 얼마나 짧고 효율적인지 보세요.'}}},
  {'name':'Catherine Parenteau','slug':'catherine-parenteau','country':'Canada','countryCode':'CAN','style':'Reliable all-court pressure with elite consistency','skills':['Consistency','Dinks under pressure','Singles construction','Mixed patterns','Error control'],'achievements':['PPA profile lists strong singles, women’s doubles, and mixed doubles rankings.','Canadian pro with a deep tennis background.','Known for high-percentage pressure and disciplined shot selection.'],'events':['Singles','Women’s doubles','Mixed doubles'],'paddle':'Paddletek / sponsored line varies by season','watch':'Study how she protects low-percentage errors under stress.','bio':'Catherine Parenteau is a Canadian professional with a strong tennis foundation and a reputation for consistency. Her matches are useful for players who want to reduce unforced errors while still applying pressure through placement, patience, and smart attacking windows.','hometown':'Montreal, Quebec, Canada','age':'31','height':'5 ft 5 in / 165 cm public listing','turnedPro':'2016','plays':'Right-handed','resides':'Naples, Florida','officialProfile':'https://ppatour.com/athlete/catherine-parenteau/','secondaryProfile':'https://pickleball.com/players/catherine-parenteau','translations':{'ko':{'style':'엘리트 수준의 안정성을 바탕으로 올라운드 압박을 만드는 선수','bio':'Catherine Parenteau는 탄탄한 테니스 기반을 가진 캐나다 프로 선수이며 안정성이 강점으로 알려져 있습니다. 언포스드 에러를 줄이면서도 배치, 인내심, 적절한 공격 타이밍으로 압박을 유지하는 방법을 배우기에 좋습니다.','watch':'압박 상황에서 낮은 확률의 실수를 어떻게 피하는지 보세요.'}}},
  {'name':'Anna Bright','slug':'anna-bright','country':'United States','countryCode':'USA','style':'Fast hands, aggressive doubles patterns, and creative attacks','skills':['Kitchen speed','Speed-up disguise','Mixed doubles reads','Counter volleys','Anticipation'],'achievements':['PPA/Pickleball.com profiles highlight her UC Berkeley tennis background and PPA Gold Card status.','Known for fast hands, consistency, and anticipation.','Top women’s doubles and mixed doubles presence.'],'events':['Women’s doubles','Mixed doubles','Singles spot starts'],'paddle':'JOOLA Anna Bright Scorpeus / sponsored line varies','watch':'Notice the disguise before speed-ups.','bio':'Anna Bright played varsity tennis at UC Berkeley before moving into professional pickleball. She is especially useful to study in doubles because her anticipation and fast hands allow her to turn small openings into quick attacks. Her background also makes her a strong example for tennis players transitioning into pickleball.','hometown':'South Florida tour base / United States','age':'26','height':'5 ft 7 in / 170 cm public listing','turnedPro':'2022','plays':'Right-handed','resides':'Pompano Beach, Florida','officialProfile':'https://ppatour.com/athlete/anna-bright/','secondaryProfile':'https://pickleball.com/players/anna-bright','translations':{'ko':{'style':'빠른 손, 공격적인 더블스 패턴, 창의적인 공격 전환이 특징인 선수','bio':'Anna Bright는 UC Berkeley 여자 테니스팀에서 활약한 뒤 프로 피클볼로 전향했습니다. 예측력과 빠른 손을 바탕으로 작은 빈틈을 즉시 공격으로 전환하기 때문에 더블스 학습에 특히 좋습니다. 테니스 경험자가 피클볼로 넘어올 때 참고하기 좋은 사례이기도 합니다.','watch':'스피드업 전에 어떤 위장 동작이 들어가는지 관찰하세요.'}}},
  {'name':'Tyson McGuffin','slug':'tyson-mcguffin','country':'United States','countryCode':'USA','style':'Athletic pressure, spin, and high-energy singles/doubles play','skills':['Serve pressure','Spin drives','Singles movement','Competitive tempo','Defensive gets'],'achievements':['PPA profile lists him as an active top-level tour player across divisions.','Long-time pro champion and ambassador figure.','Known for energy, athletic defense, and a recognizable personal brand.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'Selkirk / sponsored line varies by season','watch':'Study serve-plus-one pressure and emotional momentum.','bio':'Tyson McGuffin came through tennis and coaching before becoming one of pickleball’s best-known professional personalities. His game is useful for studying energy management, spin pressure, serve-plus-one patterns, and how athletic defense can shift momentum in singles and doubles.','hometown':'Lake Chelan / Yakima, Washington region','age':'—','height':'—','turnedPro':'2016 era','plays':'Right-handed','resides':'United States','officialProfile':'https://ppatour.com/athlete/tyson-mcguffin/','secondaryProfile':'https://pickleball.com/players/tyson-mcguffin','translations':{'ko':{'style':'운동능력, 스핀, 높은 에너지로 압박하는 싱글·더블스 선수','bio':'Tyson McGuffin은 테니스와 코칭 경력을 거쳐 피클볼의 대표적인 프로 선수이자 개성 있는 인물로 자리 잡았습니다. 에너지 관리, 스핀 압박, 서브 이후 첫 공격, 운동능력 기반 수비가 경기 흐름을 어떻게 바꾸는지 배우기 좋습니다.','watch':'서브 이후 첫 공 압박과 감정적 모멘텀을 어떻게 만드는지 보세요.'}}},
  {'name':'Riley Newman','slug':'riley-newman','country':'United States','countryCode':'USA','style':'Creative doubles systems, counters, and court coverage','skills':['Mixed doubles systems','Poaching','Counters','Partner movement','Court compression'],'achievements':['PPA profile lists strong doubles and mixed-doubles results.','Known for creative positioning and partnership systems.','Pickleball.com notes a significant PPA gold/major resume.'],'events':['Men’s doubles','Mixed doubles'],'paddle':'Sponsored equipment varies by season','watch':'Watch how early positioning creates poach opportunities.','bio':'Riley Newman is best studied through doubles. His movement, pre-positioning, poaching choices, and partnership patterns show how a team can create pressure before the ball is even struck. He is a strong model for players who want to understand court geography, not just shot mechanics.','hometown':'Whidbey Island, Washington / Phoenix training base public mentions','age':'—','height':'—','turnedPro':'2018/2019 era','plays':'Right-handed','resides':'United States','officialProfile':'https://ppatour.com/athlete/riley-newman/','secondaryProfile':'https://pickleball.com/players/riley-newman','translations':{'ko':{'style':'창의적인 더블스 시스템, 카운터, 넓은 코트 커버가 특징인 선수','bio':'Riley Newman은 더블스 관점에서 공부하기 좋습니다. 이동, 사전 포지셔닝, 포칭 판단, 파트너와의 패턴을 통해 공을 치기 전부터 압박을 만드는 방식을 보여줍니다. 샷 기술뿐 아니라 코트 지리를 이해하려는 플레이어에게 좋은 모델입니다.','watch':'초기 포지셔닝이 어떻게 포칭 기회를 만드는지 보세요.'}}},
  {'name':'James Ignatowich','slug':'james-ignatowich','country':'United States','countryCode':'USA','style':'Modern power, quick hands, and aggressive transitions','skills':['Drive attacks','Counter exchanges','Kitchen pressure','Athletic recovery','Spin pressure'],'achievements':['Pickleball.com profile notes Vanderbilt tennis and PPA Indoor National Championship golds.','Known for fast rise, aggressive style, and media/podcast presence.','Founder/associated with RPM paddle brand content.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'RPM / Selkirk history; sponsored equipment varies','watch':'Study when the drive is used to set up the next ball.','bio':'James Ignatowich came from a high-level tennis background and brought a very modern offensive approach into pickleball. He is useful to study for drive-to-crash patterns, counter battles, transition attacks, and how young pros combine content, personal branding, and competition.','hometown':'United States','age':'25 public profile listings vary','height':'—','turnedPro':'2022/2023 era','plays':'Right-handed','resides':'United States','officialProfile':'https://pickleball.com/players/james-ignatowich','secondaryProfile':'https://rpmpb.com/pages/rpm-pro-pickleball-team','translations':{'ko':{'style':'현대적인 파워, 빠른 손, 공격적인 전환이 특징인 선수','bio':'James Ignatowich는 높은 수준의 테니스 배경을 바탕으로 현대적인 공격형 피클볼을 보여주는 선수입니다. 드라이브 후 전진, 카운터 싸움, 전환 공격, 그리고 젊은 프로들이 콘텐츠·개인 브랜딩·경기를 결합하는 방식을 공부하기 좋습니다.','watch':'드라이브가 단순 득점 시도가 아니라 다음 공을 만들기 위한 수단으로 쓰이는 순간을 보세요.'}}},
  {'name':'Christian Alshon','slug':'christian-alshon','country':'United States','countryCode':'USA','style':'Powerful modern offense with fast hand battles','skills':['Power drives','Fast counters','Erne/ATP awareness','Aggressive doubles','Two-handed attacks'],'achievements':['PPA profile lists top-level results across doubles, mixed, and singles.','Pickleball.com notes University of Chicago NCAA Division III tennis championship background.','Paddletek Bantam TKO-C was designed with him.'],'events':['Singles','Men’s doubles','Mixed doubles'],'paddle':'Paddletek Bantam TKO-C / sponsored line','watch':'Watch how he creates offensive windows from transition.','bio':'Christian Alshon moved into pickleball shortly after a successful collegiate tennis career and quickly became known for power, athleticism, and highlight-level shot making. His profile is excellent for studying the modern offensive game: heavy drives, fast hands, tweener/ATP awareness, and how to pressure from transition.','hometown':'Boca Raton, Florida','age':'25','height':'6 ft 2 in / 187 cm public listing','turnedPro':'2022','plays':'Right-handed','resides':'Boca Raton, Florida','officialProfile':'https://ppatour.com/athlete/christian-alshon/','secondaryProfile':'https://pickleball.com/players/christian-alshon','translations':{'ko':{'style':'강한 현대식 공격과 빠른 손싸움을 앞세운 선수','bio':'Christian Alshon은 성공적인 대학 테니스 경력 직후 피클볼로 전향해 강한 파워, 운동능력, 하이라이트성 샷으로 빠르게 알려졌습니다. 헤비 드라이브, 빠른 손싸움, 트위너·ATP 감각, 전환구역에서의 압박을 공부하기 좋은 현대 공격형 선수입니다.','watch':'전환구역에서 어떻게 공격 창을 만들어내는지 보세요.'}}},
  {'name':'Lea Jansen','slug':'lea-jansen','country':'United States','countryCode':'USA','style':'Competitive singles patterns and disciplined pressure','skills':['Singles rally tolerance','Serve-return pressure','Pattern discipline','Mental toughness','Counter attacks'],'achievements':['PPA profile lists strong singles results and active tour presence.','Pickleball.com notes her Washington tennis background and collegiate success.','Known for intensity and singles competitiveness.'],'events':['Singles','Women’s doubles','Mixed doubles spot starts'],'paddle':'Sponsored equipment varies by season','watch':'Study how she extends points without losing attack intent.','bio':'Lea Jansen grew up in Washington with a tennis background and later became known for competitive singles patterns and a fiery on-court presence. Her matches are useful for learning patience under pressure, serve-return discipline, and when to stay in a rally rather than force a low-percentage attack.','hometown':'Spokane, Washington','age':'—','height':'—','turnedPro':'2021 era','plays':'Right-handed','resides':'United States','officialProfile':'https://ppatour.com/athlete/lea-jansen/','secondaryProfile':'https://pickleball.com/players/lea-jansen','translations':{'ko':{'style':'경쟁적인 싱글 패턴과 규율 있는 압박이 특징인 선수','bio':'Lea Jansen은 워싱턴에서 성장했고 테니스 배경을 바탕으로 강한 싱글 경쟁력과 뜨거운 코트 에너지로 알려졌습니다. 압박 상황에서의 인내심, 서브·리턴 규율, 낮은 확률의 공격을 억제하고 랠리를 이어가는 판단을 배우기 좋습니다.','watch':'공격 의도를 잃지 않으면서 포인트를 길게 끌고 가는 방식을 보세요.'}}},
  {'name':'Lucy Kovalova','slug':'lucy-kovalova','country':'Slovakia / United States scene','countryCode':'SVK','style':'Reach, counters, and elite doubles positioning','skills':['Doubles positioning','Counter reach','Mixed doubles systems','Kitchen stability','Blocking lanes'],'achievements':['PPA profile lists women’s, mixed, and singles participation.','Long-time doubles and mixed doubles standout.','Personal site describes her as one of the best women’s professional players in the game.'],'events':['Women’s doubles','Mixed doubles','Singles spot starts'],'paddle':'ONIX Evoke Premier / sponsored line history varies','watch':'Study her spacing and patience at the kitchen line.','bio':'Lucy Kovalova, originally from Slovakia, has long been associated with elite doubles and mixed-doubles play. Her height, reach, and countering ability make her a strong model for understanding lane control, disciplined blocking, and how a taller player can compress space at the kitchen line.','hometown':'Slovakia / Wichita State tennis background public mentions','age':'—','height':'—','turnedPro':'2016 era','plays':'Right-handed','resides':'United States tour scene','officialProfile':'https://ppatour.com/athlete/lucy-kovalova/','secondaryProfile':'https://www.lucykovalovapb.com/','translations':{'ko':{'style':'리치, 카운터, 엘리트 더블스 포지셔닝이 특징인 선수','bio':'슬로바키아 출신의 Lucy Kovalova는 오랫동안 엘리트 더블스와 혼합복식 플레이로 알려졌습니다. 큰 키와 리치, 카운터 능력을 바탕으로 레인 컨트롤, 안정적인 블록, 키친 라인에서 공간을 압축하는 방법을 공부하기 좋습니다.','watch':'키친 라인에서 간격과 인내심을 어떻게 유지하는지 보세요.'}}},
]

# add image and alt paths
for p in paddles:
    p['image'] = f"/assets/img/paddles/{p['slug']}.svg"
    p['imageAlt'] = f"Illustrated product card for {p['brand']} {p['model']}"
for i,pl in enumerate(players):
    pl['image'] = f"/assets/img/players/{pl['slug']}.svg"
    pl['imageAlt'] = f"Illustrated profile card for {pl['name']}"
    pl['photoNote'] = 'Illustrated placeholder. Use licensed/official photos only after permission.'

def write_js(filename, data, var_name, comment):
    body = json.dumps(data, ensure_ascii=False, indent=2)
    js = f"/* {comment} */\n(function (root, factory) {{\n  if (typeof module === 'object' && module.exports) module.exports = factory();\n  else root.{var_name} = factory();\n}}(typeof self !== 'undefined' ? self : this, function () {{\n  return {body};\n}}));\n"
    (root/'data'/filename).write_text(js, encoding='utf-8')

write_js('paddles.js', paddles, 'SITE_PADDLES', 'Enriched paddle database. Prices are USD reference prices from official/source pages and should be verified before publishing purchase advice.')
write_js('players.js', players, 'SITE_PLAYERS', 'Enriched pro player profiles. Rankings, DUPR, sponsors, and images should be checked against live official profiles before publication.')

# SVG generation
paddle_dir = root/'assets/img/paddles'
player_dir = root/'assets/img/players'
paddle_dir.mkdir(parents=True, exist_ok=True)
player_dir.mkdir(parents=True, exist_ok=True)

palette = ['#1e6f5c','#f2b84b','#e76f51','#3a86ff','#8338ec','#2a9d8f','#264653','#ff7b00','#6d597a','#43aa8b','#577590','#bc4749']

def esc_xml(s):
    return (str(s).replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;'))

def wrap_text(text, max_len=17, lines=3):
    words = text.split()
    out=[]; cur=''
    for w in words:
        if len(cur)+len(w)+1 <= max_len:
            cur = (cur+' '+w).strip()
        else:
            out.append(cur); cur=w
            if len(out) >= lines-1: break
    if cur and len(out) < lines: out.append(cur)
    return out[:lines]

shape_width = {'widebody':160,'traditional':145,'hybrid':150,'elongated':130}
def shape_key(shape):
    s=shape.lower()
    if 'widebody' in s: return 'widebody'
    if 'traditional' in s: return 'traditional'
    if 'hybrid' in s: return 'hybrid'
    return 'elongated'

def make_paddle_svg(p, idx):
    c1 = palette[idx % len(palette)]
    c2 = palette[(idx+3) % len(palette)]
    key = shape_key(p['shape'])
    w = shape_width[key]
    x = 200 - w/2
    rx = {'widebody':36,'traditional':42,'hybrid':40,'elongated':48}[key]
    body_h = {'widebody':220,'traditional':230,'hybrid':235,'elongated':255}[key]
    body_y = 58
    handle_y = body_y + body_h - 6
    handle_h = 128
    model_lines = wrap_text(p['model'], 18, 3)
    model_text = ''.join([f'<text x="200" y="{170+i*26}" class="model">{esc_xml(line)}</text>' for i,line in enumerate(model_lines)])
    traits = ' · '.join(p.get('traits', [])[:3]).upper()
    price = f"${p['priceUsd']:.2f}" if p.get('priceUsd') else p.get('priceBand','')
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="720" height="900" viewBox="0 0 400 500" role="img" aria-labelledby="title desc">
<title id="title">{esc_xml(p['brand'])} {esc_xml(p['model'])} illustrated paddle card</title>
<desc id="desc">A stylized non-photographic product card created for PickleLevel.</desc>
<defs>
  <linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{c1}"/><stop offset="1" stop-color="{c2}"/></linearGradient>
  <radialGradient id="spot" cx="50%" cy="38%" r="65%"><stop offset="0" stop-color="#fff" stop-opacity=".22"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient>
  <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="14" stdDeviation="13" flood-color="#14231f" flood-opacity=".22"/></filter>
  <style>
    .brand{{font:700 20px Arial,sans-serif;letter-spacing:.12em;fill:#ffffff;text-anchor:middle}}
    .model{{font:800 22px Arial,sans-serif;fill:#ffffff;text-anchor:middle}}
    .small{{font:700 11px Arial,sans-serif;letter-spacing:.10em;fill:#e8fff8;text-anchor:middle;opacity:.9}}
    .price{{font:900 25px Arial,sans-serif;fill:#1b2a26;text-anchor:middle}}
  </style>
</defs>
<rect width="400" height="500" rx="28" fill="#f6fbf7"/>
<rect x="20" y="20" width="360" height="460" rx="24" fill="#ffffff" stroke="#d9e8df"/>
<g filter="url(#shadow)">
  <rect x="{x:.1f}" y="{body_y}" width="{w}" height="{body_h}" rx="{rx}" fill="url(#g)"/>
  <rect x="{x:.1f}" y="{body_y}" width="{w}" height="{body_h}" rx="{rx}" fill="url(#spot)"/>
  <path d="M{200-w/2+18:.1f} {body_y+32} C {200-w/2+50:.1f} {body_y+8}, {200+w/2-50:.1f} {body_y+8}, {200+w/2-18:.1f} {body_y+32}" fill="none" stroke="#fff" stroke-opacity=".35" stroke-width="3"/>
  <rect x="174" y="{handle_y}" width="52" height="{handle_h}" rx="20" fill="#2c2f31"/>
  <rect x="179" y="{handle_y+9}" width="42" height="{handle_h-18}" rx="17" fill="#3d4448"/>
  <path d="M183 {handle_y+22} h34 M183 {handle_y+44} h34 M183 {handle_y+66} h34 M183 {handle_y+88} h34" stroke="#eaf4f1" stroke-opacity=".28" stroke-width="3"/>
</g>
<text x="200" y="112" class="brand">{esc_xml(p['brand'].upper())}</text>
{model_text}
<text x="200" y="262" class="small">{esc_xml(p['style'].replace('-', ' ').upper())} · {esc_xml(shape_key(p['shape']).upper())}</text>
<rect x="105" y="405" width="190" height="48" rx="24" fill="#f2b84b"/>
<text x="200" y="437" class="price">{esc_xml(price)}</text>
<text x="200" y="382" class="small" fill="#1e6f5c">{esc_xml(traits)}</text>
</svg>'''

for idx,p in enumerate(paddles):
    (paddle_dir/f"{p['slug']}.svg").write_text(make_paddle_svg(p, idx), encoding='utf-8')

# player cards

def initials(name):
    return ''.join([x[0] for x in name.replace('-', ' ').split()[:2]]).upper()

def make_player_svg(pl, idx):
    c1 = palette[(idx+1) % len(palette)]
    c2 = palette[(idx+6) % len(palette)]
    init = initials(pl['name'])
    name_lines = wrap_text(pl['name'], 17, 2)
    name_text = ''.join([f'<text x="200" y="{350+i*28}" class="name">{esc_xml(line)}</text>' for i,line in enumerate(name_lines)])
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="720" height="900" viewBox="0 0 400 500" role="img" aria-labelledby="title desc">
<title id="title">{esc_xml(pl['name'])} illustrated profile card</title>
<desc id="desc">A stylized placeholder profile card, not a photographic likeness.</desc>
<defs>
  <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{c1}"/><stop offset="1" stop-color="{c2}"/></linearGradient>
  <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="14" stdDeviation="14" flood-color="#14231f" flood-opacity=".25"/></filter>
  <style>
    .init{{font:900 74px Arial,sans-serif;fill:#fff;text-anchor:middle}}
    .name{{font:900 24px Arial,sans-serif;fill:#1b2a26;text-anchor:middle}}
    .small{{font:700 12px Arial,sans-serif;letter-spacing:.12em;fill:#1e6f5c;text-anchor:middle}}
    .cap{{font:700 11px Arial,sans-serif;letter-spacing:.10em;fill:#ffffff;text-anchor:middle;opacity:.88}}
  </style>
</defs>
<rect width="400" height="500" rx="28" fill="#f6fbf7"/>
<rect x="20" y="20" width="360" height="460" rx="24" fill="#ffffff" stroke="#d9e8df"/>
<g filter="url(#shadow)">
  <rect x="56" y="48" width="288" height="278" rx="34" fill="url(#bg)"/>
  <circle cx="200" cy="160" r="70" fill="#ffffff" fill-opacity=".22"/>
  <circle cx="200" cy="140" r="42" fill="#ffffff" fill-opacity=".72"/>
  <path d="M120 285c14-58 52-88 80-88s66 30 80 88" fill="#ffffff" fill-opacity=".72"/>
  <circle cx="316" cy="78" r="30" fill="#f2b84b"/>
  <text x="316" y="83" class="cap">{esc_xml(pl['countryCode'])}</text>
  <text x="200" y="183" class="init">{esc_xml(init)}</text>
</g>
{name_text}
<text x="200" y="415" class="small">{esc_xml(pl['countryCode'])} · PRO PROFILE</text>
<text x="200" y="445" class="small">ILLUSTRATED CARD</text>
</svg>'''

for idx,pl in enumerate(players):
    (player_dir/f"{pl['slug']}.svg").write_text(make_player_svg(pl, idx), encoding='utf-8')

print('enriched data and images written', len(paddles), len(players))
